# Generated by Django 2.2.10 on 2020-03-25 09:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAppPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_manager', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourlyWage', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.ShiftApp')),
                ('worker_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.ShiftApp')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('start_time', models.TimeField()),
                ('break_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_night', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.ShiftApp')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchdule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_rest_request', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.Shift')),
                ('work_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiftApp.WorkStyle')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlanWorkStyleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_style_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.WorkPlan')),
                ('work_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.WorkStyle')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftWorkerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.Shift')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.Shift')),
                ('work_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiftApp.WorkPlan')),
            ],
        ),
        migrations.AddField(
            model_name='shiftapp',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiftApp.ShiftAppPlan'),
        ),
        migrations.AddField(
            model_name='shiftapp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftApp.ShiftApp'),
        ),
        migrations.AddField(
            model_name='shift',
            name='worker',
            field=models.ManyToManyField(to='shiftApp.Worker'),
        ),
    ]
